alg: PreferenceIQL
alg_kwargs:
  expectile: 0.7
  beta: 0.33333333
  reward_steps: 20000
  # Configure offline steps. These aren't needed, but good to set.
  offline_steps: -1
  random_steps: 0

optim: Adam
optim_kwargs:
  lr: 0.0003

network: ActorCriticValueRewardPolicy
network_kwargs:
  actor_class: DiagonalGaussianMLPActor
  actor_kwargs:
    log_std_bounds: [-5, 2]
    output_act: ["import", "torch.nn", "Tanh"]
    state_dependent_log_std: False
    log_std_tanh: False
    squash_normal: False
  critic_class: ContinuousMLPCritic
  critic_kwargs:
    ensemble_size: 2
  value_class: MLPValue
  value_kwargs:
    ensemble_size: 1
  reward_class: ContinuousMLPCritic
  reward_kwargs:
    ensemble_size: 1
  hidden_layers: [256, 256]
  ortho_init: True

eval_env: hopper-medium-replay-v2

dataset: ReplayAndFeedbackBuffer
dataset_kwargs:
  replay_class: D4RLDataset
  replay_kwargs:
    name: hopper-medium-replay-v2
    distributed: False
    batch_size: 256
    discount: 0.99
    normalize_reward: True
    action_eps: 0.00001 # necesary to prevent NaN in the dataset.
  feedback_class: PairwiseComparisonDataset
  feedback_kwargs:
    path: datasets/preference_transformer/hopper-medium-replay-v2/num500_human_train.npz
    capacity: null
    batch_size: 8
    segment_size: 100
    subsample_size: 64
  discount: 0.99

schedule:
  actor: ["import", "torch.optim.lr_scheduler", "CosineAnnealingLR"]
schedule_kwargs:
  actor:
    T_max: 1000000

processor: null

trainer_kwargs: # Arguments given to Algorithm.train
  total_steps: 1000000 # The total number of steps to train
  log_freq: 500 # How often to log values
  eval_freq: 5000 # How often to run evals
  eval_fn: eval_policy
  eval_kwargs:
    num_ep: 10 # Number of enviornment episodes to run for evaluation
  loss_metric: reward # The validation metric that determines when to save the "best_checkpoint"
  train_dataloader_kwargs:
    num_workers: 0
    batch_size: null
    collate_fn: null
  profile_freq: 500

seed: null
