alg: IPL_AWAC
alg_kwargs:
  tau: 0.005
  beta: 0.3333
  chi2_coeff: 4
  chi2_replay_weight: 0.5
  policy_replay_weight: 0.5
  use_min_target: False
  use_soft_target: False
  # Configure offline steps. These aren't needed, but good to set.
  offline_steps: -1
  random_steps: 0

optim: Adam
optim_kwargs:
  lr: 0.0003

network: ActorCriticPolicy
network_kwargs:
  actor_class: DiagonalGaussianMLPActor
  actor_kwargs:
    log_std_bounds: [-5, 2]
    output_act: ["import", "torch.nn", "Tanh"]
    state_dependent_log_std: False
    log_std_tanh: False
    squash_normal: False
  critic_class: ContinuousMLPCritic
  critic_kwargs:
    ensemble_size: 1
  hidden_layers: [256, 256, 256]
  ortho_init: True

eval_env: mw_door-close-v2

dataset: ReplayAndFeedbackBuffer
dataset_kwargs:
  replay_class: EmptyDataset
  replay_kwargs:
    path: null
    distributed: False
    batch_size: 256
  feedback_class: PairwiseComparisonDataset
  feedback_kwargs:
    path: datasets/metaworld/door-close_10000.npz
    capacity: null
    batch_size: 16
    segment_size: 25
    subsample_size: 16
  discount: 0.99

schedule: null

processor: null

trainer_kwargs: # Arguments given to Algorithm.train
  total_steps: 200000 # The total number of steps to train
  log_freq: 500 # How often to log values
  eval_freq: 2500 # How often to run evals
  eval_fn: eval_policy
  eval_kwargs:
    num_ep: 20 # Number of enviornment episodes to run for evaluation
  loss_metric: reward # The validation metric that determines when to save the "best_checkpoint"
  train_dataloader_kwargs:
    num_workers: 0
    batch_size: null
    collate_fn: null
  profile_freq: 500

seed: null
